[project]
name = "sympy-playground"
version = "0.1.0"
description = "Add a short description here"
authors = ["Vitor Shen <17490173+shenvitor@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
docnb = """
sphinx-build \
    -nW --keep-going \
    -b html \
    docs _build/html
"""
docnblive = """
sphinx-autobuild \
    --watch docs \
    -nW --keep-going \
    -b html \
    docs _build/html
"""

[dependencies]
sympy = ">=1.12,<2"
jupyterlab = ">=4.1.5,<4.2"
black = ">=24.3.0,<24.4"
python = "3.11.*"
jupyterlab-git = ">=0.50.0,<0.51"
jupyterlab_code_formatter = ">=2.2.1,<2.3"
isort = ">=5.13.2,<5.14"
jupyterlab-lsp = ">=5.1.0,<5.2"
pre-commit = ">=3.7.0,<3.8"
jupyterlab-myst = ">=2.3.2,<2.4"
nodejs = ">=20.9.0,<20.10"
numpy = ">=1.26.4,<1.27"
graphviz = ">=9.0.0,<9.1"
tensorflow = ">=2.15.0,<2.16"
python-graphviz = ">=0.20.3,<0.21"
scipy = ">=1.13.0,<1.14"
myst-nb = ">=1.1.0,<1.2"
sphinx-autobuild = "2024.2.*"
