[project]
name = "sympy-playground"
version = "0.1.0"
description = "Add a short description here"
authors = ["Vitor Shen <17490173+shenvitor@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
