[project]
name = "sympy-playground"
version = "0.1.0"
description = "Add a short description here"
authors = ["Vitor Shen <17490173+shenvitor@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
sympy = ">=1.12,<2"
jupyterlab = ">=4.1.5,<4.2"
black = ">=24.3.0,<24.4"
python = ">=3.12.2,<3.13"
jupyterlab-git = ">=0.50.0,<0.51"
jupyterlab_code_formatter = ">=2.2.1,<2.3"
isort = ">=5.13.2,<5.14"
jupyterlab-lsp = ">=5.1.0,<5.2"
pre-commit = ">=3.7.0,<3.8"
